In [1]:
import pandas as pd
import numpy as np

In [94]:
data = pd.read_csv('Data/Train/Xtr0.csv', sep = ' ', header=None).values
y = pd.read_csv('Data/Train/Ytr0.csv', sep=',', index_col=0).ix[:,0].values

In [71]:
y[:10]

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0])

In [95]:
data[:10]

array([['TCCTCAACTTTTATTGGGCCGCTGTGGCACCAGAATCTACGAATGGCGCCCTCTAGAGTTGTGTAAAGAAGTGGCGTCACCTCATTATAAATAAAAGGTTG'],
       ['CGGAGTGATTCAGCAAGAAGGCTCAGACCATTTACACTTCTCCTCACAGGGCAAAGACTTCTCAGAGACAACTAATATGGCCTAGTGCCTAGTCATTGGAC'],
       ['GCCTCAGGCACTCTCCAGATGGTTAAGATATGGTGTAAGTGTATGTGCGTGTCTGGCTGCAGTTGATAGTTGGGCAAAGAGGAAACTATCACAAAGAGGAA'],
       ['TCAGTCGCCTGGCCTTCCAGCCTCACAGGCAAGATAAGCCACCCTCACAGACTTCTCTGTGCTCCCATCTAAACATCTAAATCAGCCATCTGGTTTCCTTA'],
       ['CTTAATGGAAAAATTAGATTATGGGTTGGCTTACCTGGATTTACCTAGAGTGTCTGCCATGTCTATCAATTGGATTACGGGGCTTTTATTGATTAGGGGGA'],
       ['GAAACAAGCTAATATAAGGTGGGGGCCTGAAAATTTTATCCAATGGTCATTTAAGAATCGCAATCAATGTCCTCTAGATATATAATTCACCTAAATACGGA'],
       ['CTTTCTTATCTGTGTGGCTGTGGGCGTGTCTTTGGCAAGCCCCACTGTGAGAGTTCCCTTATCTATGCCTGCAGGCTGTTCTTTTATTTGAAAGAATTCAG'],
       ['TGATTACTGCATGGAAAAGGGGCCAGGGCAATTACTAGAGGGCTCAATCCCAGTAAGGGGATGTGTACCAGGGAGGGTTGCTTTGACAGGAGATCAGTCTA'],
       ['GAGATTCTTAACATGCAACCACAAATCGATGCAGTTATGGATCATGTTGAATGGCAACTCACCTGGCAGTGGAGAGCAG

In [101]:
mapped = np.apply_along_axis(lambda row: list(row[0]), 1, data)

In [102]:
def generate_variables(row):
    n = len(row)
    map_letters = dict({'A' : 0, 'T' : 1, 'C' : 2, 'G' : 3})
    variables = np.zeros([4*n])
    for i in range(n):
        variables[4*i + map_letters[row[i]]] = 1
    return variables

In [103]:
variables = np.apply_along_axis(generate_variables, 1, mapped)

In [104]:
variables.shape

(2000, 404)

In [105]:
from learning_models import SVM, KRR

In [107]:
from tools import train_test_split
from kernels import polynomial_kernel_matrix, gaussian_kernel_matrix

In [108]:
K = polynomial_kernel_matrix(variables)

In [110]:
X_train, X_test, y_train, y_test, K_train, K_test = train_test_split(variables, y, K)

Total number of examples : 2000
Ratio of positive samples : 0.50
Ratio of negative to positive labels in the data : 1.00


In [111]:
svm = SVM()

In [112]:
svm.train(K_train, y_train)

/Users/karlhajjar/anaconda/lib/python3.5/site-packages/cvxopt/coneprog.py:2111: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 'x' in initvals:
/Users/karlhajjar/anaconda/lib/python3.5/site-packages/cvxopt/coneprog.py:2116: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 's' in initvals:
/Users/karlhajjar/anaconda/lib/python3.5/site-packages/cvxopt/coneprog.py:2131: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 'y' in initvals:
/Users/karlhajjar/anaconda/lib/python3.5/site-packages/cvxopt/coneprog.py:2136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 'z' in initvals:


     pcost       dcost       gap    pres   dres
 0:  0.0000e+00 -1.0000e+00  4e+03  6e+01  1e+00
 1: -4.9880e-01 -1.4004e+00  4e+01  6e-01  1e-02
 2: -3.6224e-01 -1.3211e+00  1e+00  7e-03  1e-04
 3: -4.4310e-01 -5.6255e-01  1e-01  5e-04  8e-06
 4: -5.0289e-01 -5.0650e-01  4e-03  5e-06  9e-08
 5: -5.0363e-01 -5.0435e-01  7e-04  1e-06  2e-08
 6: -5.0372e-01 -5.0404e-01  3e-04  8e-08  1e-09
 7: -5.0378e-01 -5.0389e-01  1e-04  5e-09  8e-11
 8: -5.0380e-01 -5.0383e-01  3e-05  4e-10  7e-12
 9: -5.0381e-01 -5.0381e-01  6e-06  2e-11  3e-13
10: -5.0381e-01 -5.0381e-01  1e-06  2e-12  3e-14
11: -5.0381e-01 -5.0381e-01  2e-07  2e-14  7e-16
Optimal solution found.


In [113]:
y_pred = svm.predict(K_test)

In [115]:
y_pred

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
1 - np.mean(np.abs(y_pred - y_test))

0.5

In [117]:
y_test

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1])

In [118]:
len(y_test[y_test==1])

100

In [119]:
len(y_test[y_test==0])

100

In [39]:
generate_variables(mapped[0,:])

array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0.

In [41]:
mapped[0,:]

array(['T', 'C', 'C', 'T', 'C', 'A', 'A', 'C', 'T', 'T', 'T', 'T', 'A',
       'T', 'T', 'G', 'G', 'G', 'C', 'C', 'G', 'C', 'T', 'G', 'T', 'G',
       'G', 'C', 'A', 'C', 'C', 'A', 'G', 'A', 'A', 'T', 'C', 'T', 'A',
       'C', 'G', 'A', 'A', 'T', 'G', 'G', 'C', 'G', 'C', 'C', 'C', 'T',
       'C', 'T', 'A', 'G', 'A', 'G', 'T', 'T', 'G', 'T', 'G', 'T', 'A',
       'A', 'A', 'G', 'A', 'A', 'G', 'T', 'G', 'G', 'C', 'G', 'T', 'C',
       'A', 'C', 'C', 'T', 'C', 'A', 'T', 'T', 'A', 'T', 'A', 'A', 'A',
       'T', 'A', 'A', 'A', 'A', 'G', 'G', 'T', 'T', 'G'], dtype='<U1')

In [24]:
list(mapped)

[['T',
  'C',
  'C',
  'T',
  'C',
  'A',
  'A',
  'C',
  'T',
  'T',
  'T',
  'T',
  'A',
  'T',
  'T',
  'G',
  'G',
  'G',
  'C',
  'C',
  'G',
  'C',
  'T',
  'G',
  'T',
  'G',
  'G',
  'C',
  'A',
  'C',
  'C',
  'A',
  'G',
  'A',
  'A',
  'T',
  'C',
  'T',
  'A',
  'C',
  'G',
  'A',
  'A',
  'T',
  'G',
  'G',
  'C',
  'G',
  'C',
  'C',
  'C',
  'T',
  'C',
  'T',
  'A',
  'G',
  'A',
  'G',
  'T',
  'T',
  'G',
  'T',
  'G',
  'T',
  'A',
  'A',
  'A',
  'G',
  'A',
  'A',
  'G',
  'T',
  'G',
  'G',
  'C',
  'G',
  'T',
  'C',
  'A',
  'C',
  'C',
  'T',
  'C',
  'A',
  'T',
  'T',
  'A',
  'T',
  'A',
  'A',
  'A',
  'T',
  'A',
  'A',
  'A',
  'A',
  'G',
  'G',
  'T',
  'T',
  'G'],
 ['C',
  'G',
  'G',
  'A',
  'G',
  'T',
  'G',
  'A',
  'T',
  'T',
  'C',
  'A',
  'G',
  'C',
  'A',
  'A',
  'G',
  'A',
  'A',
  'G',
  'G',
  'C',
  'T',
  'C',
  'A',
  'G',
  'A',
  'C',
  'C',
  'A',
  'T',
  'T',
  'T',
  'A',
  'C',
  'A',
  'C',
  'T',
  'T',
  'C',
  'T',
  'C'

In [4]:
len(data[0])

2000

In [5]:
len(data)

2000

In [7]:
len(data.ix[0])

1

In [10]:
s = data.ix[0].values

In [11]:
s

array(['TCCTCAACTTTTATTGGGCCGCTGTGGCACCAGAATCTACGAATGGCGCCCTCTAGAGTTGTGTAAAGAAGTGGCGTCACCTCATTATAAATAAAAGGTTG'],
      dtype=object)

In [12]:
len(s[0])

101

In [14]:
for i in range(len(data)):
    if len(data.ix[0][0]) != 101:
        print('Length of DNA sequence at line {} = {}'.format(i, len(data.ix[0][0])))